---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-admin
  namespace: "{{ .Release.namespace }}"
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "fullname" . }}-role
  namespace: "{{ .Release.namespace }}"
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["list","get"]
- apiGroups: [""]
  resources: ["pods/exec","services/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","create","delete"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "fullname" . }}-rb
  namespace: "{{ .Release.namespace }}"
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}-admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-init
  namespace: "{{ .Release.namespace }}"
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
    #!/bin/bash
    sleep 15
    kubectl exec -i svc/{{ template "fullname" . }}-ssh -n ${NAMESPACE} -- /bin/bash -c "su git -c 'gitea admin create-user --random-password --email ${USER_EMAIL} --username ${USER_NAME} --access-token --admin'" > /tmp/tmpdata/.log.txt
    echo "User Output"
    cat /tmp/tmpdata/.log.txt
    echo "User Output End"
    TOKEN=$(cat /tmp/tmpdata/.log.txt | grep 'Access token was successfully created.*' | sed 's/.* //g')
    echo "token=${TOKEN}" > /tmp/tmpdata/.log.txt
    echo $(cat /tmp/tmpdata/.log.txt)
    kubectl delete secret ${GITEA_ADMIN_SECRET_NAME} -n ${NAMESPACE}
    kubectl create secret generic ${GITEA_ADMIN_SECRET_NAME} -n ${NAMESPACE} --from-env-file=/tmp/tmpdata/.log.txt
    echo "created admin token secret: '${GITEA_ADMIN_SECRET_NAME}' in '${NAMESPACE}' created"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-init
  namespace: "{{ .Release.namespace }}"
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    spec:
      serviceAccountName: {{ template "fullname" . }}-admin
      containers:
      - name: pi
        image: bitnami/kubectl
        command: ["/usr/local/bin/entrypoint.sh"]
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GITEA_ADMIN_SECRET_NAME
          value: "gitea-admin-token"
        - name: POD_SELECTOR
          value: "app=p3s-gitea-gitea"
        - name: USER_NAME
          value: "localadmin"
        - name: USER_EMAIL
          value: "localadmin@locahost.local"
        volumeMounts:
        - name: tmpdata
          mountPath: /tmp/tmpdata
        - name: configmap-volume
          mountPath: /usr/local/bin/entrypoint.sh
          readOnly: true
          subPath: entrypoint.sh
      volumes:
      - name: tmpdata
        emptyDir: {}
      - name: configmap-volume
        configMap:
          defaultMode: 0744
          name: {{ template "fullname" . }}-init
      restartPolicy: Never
  backoffLimit: 4
